"""add check constraint

Revision ID: 14a057245402
Revises: 3eff5669118f
Create Date: 2017-04-07 11:51:11.134853

"""

# revision identifiers, used by Alembic.
from sqlalchemy import column
from sqlalchemy import func

revision = '14a057245402'
down_revision = '3eff5669118f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('price', sa.Float(precision=10, asdecimal=2), nullable=True))
    op.create_check_constraint("ck_book_price_positive", "book", "price >0")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_book_price_positive", 'book')
    op.drop_column('book', 'price')
    # ### end Alembic commands ###
