"""empty message

Revision ID: 1e2f974bbe49
Revises: 5fc75ef1446f
Create Date: 2017-02-07 10:31:09.405985

"""

# revision identifiers, used by Alembic.
revision = '1e2f974bbe49'
down_revision = '5fc75ef1446f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
