"""empty message

Revision ID: b264c836f5e9
Revises: 265f2fbff29e
Create Date: 2017-02-23 18:12:58.563938

"""

# revision identifiers, used by Alembic.
revision = 'b264c836f5e9'
down_revision = '265f2fbff29e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'book_id')
    # ### end Alembic commands ###
