"""empty message

Revision ID: c958e0220a50
Revises: 9dfd60727023
Create Date: 2017-03-28 17:40:00.090474

"""

# revision identifiers, used by Alembic.
revision = 'c958e0220a50'
down_revision = '9dfd60727023'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_book_name'), 'book', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_name'), table_name='book')
    # ### end Alembic commands ###
