"""empty message

Revision ID: d6a47e98705b
Revises: cb2267c2400a
Create Date: 2016-10-10 10:05:46.503304

"""

# revision identifiers, used by Alembic.
revision = 'd6a47e98705b'
down_revision = 'cb2267c2400a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    ### end Alembic commands ###
